CPU:
  - changed-files:
      - any-glob-to-any-file: 'ggml/src/ggml-cpu/**'
ROCm:
  - changed-files:
      - any-glob-to-any-file:
          - 'ggml/src/ggml-hip/**'
          - 'ggml/src/ggml-cuda/**'
Vulkan:
  - changed-files:
      - any-glob-to-any-file: 'ggml/src/ggml-vulkan/**'
GUI:
  - changed-files:
      - any-glob-to-any-file: 'gui/**'
Documentation:
  - changed-files:
      - any-glob-to-any-file:
          - 'docs/**'
          - '*.md'
