name: CPU CI

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths:
      - '.github/workflows/build.yml'
      - '**/CMakeLists.txt'
      - '**/*.cmake'
      - '**/*.h'
      - '**/*.hpp'
      - '**/*.c'
      - '**/*.cpp'
      - 'gui/**/*.py'
  pull_request:
    paths:
      - '.github/workflows/build.yml'
      - '**/CMakeLists.txt'
      - '**/*.cmake'
      - '**/*.h'
      - '**/*.hpp'
      - '**/*.c'
      - '**/*.cpp'
      - 'gui/**/*.py'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cpu:
    strategy:
      matrix:
        include:
          - os: ubuntu-24.04
            generator: Ninja
          - os: windows-2025
            generator: Ninja
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@v6
      - name: Configure
        run: cmake -S . -B build -G "${{ matrix.generator }}" -DGGML_CPU=ON -DGGML_VULKAN=OFF -DGGML_HIP=OFF -DLLAMA_BUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Release
      - name: Build
        run: cmake --build build -j 2
      - name: Test
        run: ctest --test-dir build -L main --output-on-failure --timeout 900
      - name: Python syntax
        run: python -m compileall -q gui scripts run.py
